name: loco
description: LoCo - Logical Components
version: 0.0.1
homepage: https://github.com/dartlib/loco.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  rxdart: ^0.22.6

dev_dependencies:
  pedantic: ^1.8.0+1
  test: 1.6.3

